import {useSession, } from "next-auth/react";
import Head from "next/head";
import Login from "~/components/login";
import { api, type RouterOutputs } from "~/utils/api";
import Layout from "~/components/layout";
import { type NextPage } from "next";
import { useState } from "react";
import {AppRouter} from '~/server/api/root'


const CreateProfileWizard = () => {
  const {data: sessionData, status} = useSession();
  
  if (!status) return null;

  return <div>
   <img 
   src={sessionData?.user.image}
   alt="Profile Picture"
   className="rounded-full w-16 h-16"
   >
   </img>
  </div>
}

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Storage Box</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-white">
      { CreateProfileWizard() }
        <Layout/>  
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tigh">
            Storage Box  
          </h1>     
          <div className="bg-red-600">
            <Login/>
            
          </div>
          <div> 
            <Content/>
          </div>
        </div>
      </main>
    </>
  );
}
export default Home;

type Post = RouterOutputs["post"]["getAll"][0];

const Content = (props: Post) =>{
  const {data: sessionData} = useSession();
  //const {selectedPost, setSelectedPost} = useState<Post | null>(null);

  const {data: posts, refetch: refetchPost} = api.post.getAll.useQuery(
    undefined,
    { 
      enabled: sessionData?.user != undefined,
    }
  );
    /*
  const createPost = api.post.create.useMutation({
    onSuccess: () => {
      void refetchPost();
    },
  });
*/
  return(
    <div>
      <ul>
          {posts?.map((post) => (
            <li key={post.id}>
              <div>
              {post.content}
              </div>
            </li>
          ))}
      </ul>
      
    </div>
  )
};

