import {useSession, } from "next-auth/react";
import Head from "next/head";
import Login from "~/components/login";
import { type NextPage } from "next";
import { StandardDropzone } from "~/components/dropzone";

const Home: NextPage = () => {
  const {data: sessionData} = useSession();
  return (
    <>
      <Head>
        <title>Storage Box</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center">
      {sessionData
      &&
      <img 
      src={sessionData?.user.image}
      alt="Profile Picture"
      className="rounded-full w-16 h-16"
      >
      </img>}    
          <h1 className="text-5xl font-extrabold tracking-tigher text-lime-500 horizontal">
            Storage Box  
          </h1>     
          <div className="bg-red-600">
            <Login/>
          </div>
          <div> 
            {sessionData &&
            <StandardDropzone/>
            }
          </div>
      </main>
    </>
  );
}

export default Home;