import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Login from "~/components/login";
import { api } from "~/utils/api";
import Layout from "~/components/layout";

export default function Home() {

  return (
    <>
      <Head>
        <title>Storage Box</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-white">
        <Layout/>  
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tigh">
            Storage Box  
          </h1>     
          <div className="bg-red-600">
            <Login/>
          </div>
        </div>
      </main>
    </>
  );
}